
// This file is the Vercel serverless entry point.
// api/server.js is generated by `bundle-for-vercel.mjs` during the build step.
// It contains the bundled Hono + React Router SSR server.
export { default, config } from './server.js';
